/**
 * Ultra-lightweight static file server for the Next.js export.
 * Replaces `next dev` to avoid Turbopack runtime compilation and OOMs.
 *
 * Usage: node serve-static.mjs
 * Port:  3000
 * Root:  ./out (generated by `next build` with output: "export")
 */

import { readFile, stat } from "node:fs/promises";
import { createServer } from "node:http";
import { extname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const PORT = Number(process.env.PORT ?? 3000);
const ROOT = resolve(fileURLToPath(new URL(".", import.meta.url)), "out");

const MIME = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml",
  ".map": "application/json",
  ".webp": "image/webp",
  ".avif": "image/avif",
};

function mimeOf(ext) {
  return MIME[ext] ?? "application/octet-stream";
}

async function resolveFile(urlPath) {
  const clean = decodeURIComponent(urlPath.split("?")[0]);
  const safe = resolve(ROOT, clean.startsWith("/") ? clean.slice(1) : clean);

  if (!safe.startsWith(ROOT)) return null;

  for (const candidate of [safe, `${safe}.html`, join(safe, "index.html")]) {
    try {
      const fileStat = await stat(candidate);
      if (fileStat.isFile()) return candidate;
    } catch {
      // Try the next static export path shape.
    }
  }

  return null;
}

async function sendFile(res, filePath, status = 200) {
  const body = await readFile(filePath);
  res.writeHead(status, { "Content-Type": mimeOf(extname(filePath)) });
  res.end(body);
}

createServer(async (req, res) => {
  try {
    const url = new URL(req.url ?? "/", `http://${req.headers.host ?? "localhost"}`);
    const filePath = await resolveFile(url.pathname);

    if (filePath) {
      await sendFile(res, filePath);
      return;
    }

    try {
      await sendFile(res, join(ROOT, "404.html"), 404);
    } catch {
      res.writeHead(404, { "Content-Type": "text/plain; charset=utf-8" });
      res.end("Not Found");
    }
  } catch (error) {
    console.error(error);
    res.writeHead(500, { "Content-Type": "text/plain; charset=utf-8" });
    res.end("Internal Server Error");
  }
}).listen(PORT, () => {
  console.log(`Static server running at http://localhost:${PORT} (root: ${ROOT})`);
});
