/**
 * Ultra-lightweight static file server for the Next.js export.
 * Replaces `next dev` (Turbopack) to avoid OOM in memory-constrained sandboxes.
 *
 * Usage:  bun serve-static.ts
 * Port:   3000
 * Root:   ./out  (generated by `next build` with output: "export")
 */

import { readdir, stat, readFile } from "node:fs/promises";
import { join, extname, resolve } from "node:path";

const PORT = 3000;
const ROOT = resolve(import.meta.dir, "out");

/* ── MIME map ──────────────────────────────────────────────── */
const MIME: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".mjs": "application/javascript; charset=utf-8",
  ".json": "application/json; charset=utf-8",
  ".png": "image/png",
  ".jpg": "image/jpeg",
  ".jpeg": "image/jpeg",
  ".gif": "image/gif",
  ".svg": "image/svg+xml",
  ".ico": "image/x-icon",
  ".woff": "font/woff",
  ".woff2": "font/woff2",
  ".ttf": "font/ttf",
  ".otf": "font/otf",
  ".txt": "text/plain; charset=utf-8",
  ".xml": "application/xml",
  ".map": "application/json",
  ".webp": "image/webp",
  ".avif": "image/avif",
};

function mimeOf(ext: string): string {
  return MIME[ext] ?? "application/octet-stream";
}

/* ── Resolve path to a real file ───────────────────────────── */
async function resolveFile(urlPath: string): Promise<string | null> {
  // Normalise: strip query string, decode, collapse // ..
  const clean = decodeURIComponent(urlPath.split("?")[0]);

  // Security: prevent directory traversal
  const safe = resolve(ROOT, clean.startsWith("/") ? clean.slice(1) : clean);
  if (!safe.startsWith(ROOT)) return null;

  // 1) Exact file match
  try {
    const s = await stat(safe);
    if (s.isFile()) return safe;
  } catch {}

  // 2) path.html
  try {
    const s = await stat(safe + ".html");
    if (s.isFile()) return safe + ".html";
  } catch {}

  // 3) path/index.html
  try {
    const s = await stat(join(safe, "index.html"));
    if (s.isFile()) return join(safe, "index.html");
  } catch {}

  return null;
}

/* ── Bun server ────────────────────────────────────────────── */
const server = Bun.serve({
  port: PORT,
  async fetch(req) {
    const url = new URL(req.url);
    const filePath = await resolveFile(url.pathname);

    if (filePath) {
      const ext = extname(filePath);
      const body = await readFile(filePath);
      return new Response(body, {
        headers: { "Content-Type": mimeOf(ext) },
      });
    }

    // 404 – try custom 404.html, else plain text
    try {
      const f404 = await readFile(join(ROOT, "404.html"));
      return new Response(f404, {
        status: 404,
        headers: { "Content-Type": "text/html; charset=utf-8" },
      });
    } catch {
      return new Response("Not Found", { status: 404 });
    }
  },
});

console.log(
  `✅ Static server running at http://localhost:${PORT}  (root: ${ROOT})`
);
